# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de0e2ad5f4195a0800d51bfc74c07da5e8666d17560eacb1bbe0e634fe4c7116c4ed1538c0518148f109a0451eb8fd83727eaa7b6d6566e659c4437bbfe43456

test:
  secret_key_base: efa4980304b128cc575471d8840c925f4192247582b943537840c538c3a72e91f729f99e13341f0a2284be84aa2bc241dd08f7750d4db453f016449b69dcb2d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
